export const Genres = [
  { value: "Action and Adventure", label: "Екшън и приключенски" },
  { value: "Classics", label: "Класика" },
  { value: "Comic Book or Graphic Novel", label: "Комикс или графичен роман" },
  { value: "Mystery", label: "Mистерия" },
  { value: "Historical Fiction", label: "Историческа художествена литература" },
  { value: "Horror", label: "Ужаси" },
  { value: "Literary Fiction", label: "Художествена литература" },
  { value: "Romance", label: "Роман" },
  { value: "Sci-Fi", label: "Научна фантастика" },
  { value: "Short Stories", label: "Кратки истории" },
  { value: "Thrillers", label: "Трилър" },
  {
    value: "Biographies and Autobiographies",
    label: "Биографии и автобиографии",
  },
  { value: "Cookbooks", label: "Готварски книги" },
  { value: "History", label: "Исторически книги" },
  { value: "Memoir", label: "Мемоари" },
  { value: "Poetry", label: "Поезия" },
  { value: "True Crime", label: "Истински истории" },
];
